name: "Schema Migrations"

on:
  push:
    paths:
      - '**/*.orion'

jobs:
  migrate:
    name: Migrate Orion Schema
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Initialize db folder, version file and migrations directory
        run: |
          # Ensure db/ directory exists
          if [ ! -d db ]; then
            mkdir db
            echo "Created db directory"
          fi

          # If version file doesn't exist under db/, create it with “0”
          if [ ! -f db/orion_schema_version.txt ]; then
            echo "0" > db/orion_schema_version.txt
            echo "Created db/orion_schema_version.txt with initial version 0"
          fi

          # Ensure db/migrations/ directory exists
          if [ ! -d db/migrations ]; then
            mkdir -p db/migrations
            echo "Created db/migrations directory"
          fi

      - name: Commit initial db structure if created
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: initialize db/orion_schema_version.txt and db/migrations/"
          file_pattern: |
            db/orion_schema_version.txt
            db/migrations/**

      # Aquí irían tus pasos de bump de versión, generación y aplicación de migraciones…
