name: "Orion Schema Versioning"

on:
  push:
    branches:
      - main

jobs:
  version:
    name: Version Schema
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Check commit message
        id: check_msg
        run: |
          MSG="${{ github.event.head_commit.message }}"
          echo "Commit message: $MSG"
          if ! echo "$MSG" | grep -qE '^orion\(accept\): [^ ]+\.orion$'; then
            echo "Not an accept commit – skipping."
            exit 78
          fi
          NAME=$(echo "$MSG" | awk '{ print $2 }')
          echo "schema=$NAME" >> $GITHUB_OUTPUT

      - name: Ensure db structure
        run: |
          mkdir -p db/migrations
          if [ ! -f db/orion_schema_version.txt ]; then
            echo "-1" > db/orion_schema_version.txt
          fi

      - name: Bump version
        id: bump
        run: |
          CUR=$(cat db/orion_schema_version.txt)
          NEXT=$((CUR + 1))
          echo "$NEXT" > db/orion_schema_version.txt
          echo "next=$NEXT" >> $GITHUB_OUTPUT

      - name: Commit version bump
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: schema version v${{ steps.bump.outputs.next }} (${{ steps.check_msg.outputs.schema }})"
          file_pattern: db/orion_schema_version.txt
