name: "Orion Schema Versioning"

on:
  push:
    branches: [ main ]

jobs:
  version:
    name: Version Schema
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Check commit message for accept
        id: check_msg
        run: |
          MSG="${{ github.event.head_commit.message }}"
          echo "Commit message: $MSG"
          if ! echo "$MSG" | grep -qE '^orion\(accept\): [^,]+,[^ ]+'; then
            echo "Not an accept commit – skipping."
            exit 78
          fi
          SCHEMA=$(echo "$MSG" | sed -E 's/^orion\(accept\): ([^,]+),.*$/\1/')
          DESC=$(echo "$MSG" | sed -E 's/^orion\(accept\): [^,]+,(.*)$/\1/')
          echo "schema=$SCHEMA" >> $GITHUB_OUTPUT
          echo "description=$DESC" >> $GITHUB_OUTPUT

      - name: Ensure db and version files
        run: |
          mkdir -p db/migrations
          if [ ! -f db/orion_schema_version.txt ]; then
            echo "-1" > db/orion_schema_version.txt
          fi
          if [ ! -f db/version_table.md ]; then
            cat > db/version_table.md <<-EOF
            # Orion Schema Version History

            | Version | Fichero \`.orion\` | Descripción | Fecha | Commit SHA |
            |:-------:|:-----------------|:-----------:|:-----:|:----------:|
            EOF
          fi

      - name: Bump version
        id: bump
        run: |
          CUR=$(cat db/orion_schema_version.txt)
          NEXT=$((CUR + 1))
          echo "$NEXT" > db/orion_schema_version.txt
          echo "next=$NEXT" >> $GITHUB_OUTPUT

      - name: Append new row to version_table.md
        run: |
          V="${{ steps.bump.outputs.next }}"
          SCHEMA="${{ steps.check_msg.outputs.schema }}"
          DESC="${{ steps.check_msg.outputs.description }}"
          DATE="$(date '+%Y-%m-%d %H:%M %Z')"
          SHA="${GITHUB_SHA::7}"
          printf "| %s | %s | %s | %s | %s |\n" \
            "$V" "$SCHEMA" "$DESC" "$DATE" "$SHA" \
            >> db/version_table.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: schema v${{ steps.bump.outputs.next }} accept ${{ steps.check_msg.outputs.schema }}"
          file_pattern: |
            db/orion_schema_version.txt
            db/version_table.md
            db/migrations/**
