name: "Schema Migrations"

on:
  push:
    paths:
      - '**/*.orion'

jobs:
  migrate:
    name: Migrate Orion Schema
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # (para poder commitear el version file y la migración)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Initialize version file and migrations folder
        run: |
          # Si no existe el fichero de versión, créalo en la raíz con “0”
          if [ ! -f orion_schema_version.txt ]; then
            echo "0" > orion_schema_version.txt
            echo "Created orion_schema_version.txt with initial version 0"
          fi

          # Si no existe la carpeta db/migrations, créala
          if [ ! -d db/migrations ]; then
            mkdir -p db/migrations
            echo "Created db/migrations directory"
          fi

      - name: Commit initial version file if created
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: initialize schema version and migrations folder"
          file_pattern: |
            orion_schema_version.txt
            db/migrations/**

      # ( Aquí irían luego tus pasos de bump de versión, generación de migraciones, aplicación, etc. )






